// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface NewPayload {
    "name"?: string;
    "json": string;
    "tags"?: string[] | null;
    "metadata"?: PayloadMetadata;
}

export interface Payload {
    "id": string;
    "name"?: string;
    "json": string;
    "createdAt": number;
    "tags": string[] | null;
    "metadata"?: PayloadMetadata;
}

export interface PayloadMetadata {
    "source_system"?: string;
    "type"?: string;
    "queue_uri"?: string;
    "created_at"?: string;
}

export interface PayloadUpdate {
    "id": string;
    "name"?: string | null;
    "json"?: string | null;
    "tags"?: string[] | null;
    "metadata"?: PayloadMetadata | null;
}

export interface TextDiffDraft {
    "originalText": string;
    "changedText": string;
    "viewMode": string;
    "updatedAt": number;
}

export interface WorkspaceState {
    "payloads": Payload[] | null;
    "selectedPayloadId": string | null;
    "textDiffDraft": TextDiffDraft;
    "settings": { [_ in string]?: any } | null;
}
