// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function OpenBase64TextFile(): $CancellablePromise<$models.OpenTextResult> {
    return $Call.ByID(3671241049);
}

export function SaveDecodedPDF(defaultName: string, data: string | null): $CancellablePromise<$models.SaveResult> {
    return $Call.ByID(1472345682, defaultName, data);
}
