// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as FileService from "./fileservice.js";
import * as PayloadService from "./payloadservice.js";
import * as WorkspaceService from "./workspaceservice.js";
export {
    FileService,
    PayloadService,
    WorkspaceService
};

export type {
    OpenTextResult,
    RecoveryInfo,
    SaveResult,
    WorkspaceLoadResult
} from "./models.js";
