// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";

export interface OpenTextResult {
    "cancelled": boolean;
    "name"?: string;
    "text"?: string;
}

export interface RecoveryInfo {
    "message": string;
    "databasePath": string;
    "logPath": string;
}

export interface SaveResult {
    "cancelled": boolean;
    "path"?: string;
}

export interface WorkspaceLoadResult {
    "state"?: storage$0.WorkspaceState | null;
    "recovery"?: RecoveryInfo | null;
}
