// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";

export function CreateBatch(payloads: storage$0.NewPayload[] | null): $CancellablePromise<storage$0.Payload[] | null> {
    return $Call.ByID(523507481, payloads);
}

export function Delete(ids: string[] | null): $CancellablePromise<storage$0.Payload[] | null> {
    return $Call.ByID(1614141852, ids);
}

export function List(): $CancellablePromise<storage$0.Payload[] | null> {
    return $Call.ByID(3864198151);
}

export function Restore(payloads: storage$0.Payload[] | null): $CancellablePromise<void> {
    return $Call.ByID(955305959, payloads);
}

export function Select(id: string | null): $CancellablePromise<void> {
    return $Call.ByID(2439765263, id);
}

export function Update(update: storage$0.PayloadUpdate): $CancellablePromise<storage$0.Payload> {
    return $Call.ByID(1792740206, update);
}
