// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Load(): $CancellablePromise<$models.WorkspaceLoadResult> {
    return $Call.ByID(492518084);
}

export function SaveSettings(settings: { [_ in string]?: any } | null): $CancellablePromise<void> {
    return $Call.ByID(2512717576, settings);
}

export function SaveTextDiffDraft(draft: storage$0.TextDiffDraft): $CancellablePromise<void> {
    return $Call.ByID(476209828, draft);
}
